services:
    user_management_db:
        image: postgres:16.8-alpine3.21
        container_name: user_management_db
        volumes:
            - user_management_vol:/var/lib/postgresql/data
        restart: always
        shm_size: 128mb
        env_file:
            - .env
        ports:
            - "5432:5432"

volumes:
    user_management_vol: